### ISSUE TITLE
Mitgliedergruppen, Sonderrechte, kommissarische Berufung

### ISSUE THREAD

**Issue by StephanJanosch** [DE-RSE/gruendung#1]
aus http://www.vereinsknowhow.de/kurzinfos/leitfaden.htm#7

Beachten müssen Sie vor allem, dass eine Reihe von Bestimmungen nur durch die Satzung wirksam getroffen werden können. Beschlüsse von Vorstand oder Mitgliederversammlung reichen dann nicht aus. Das gilt z.B. für

die Festlegung verschiedener Mitgliedergruppen (mit unterschiedlichen Rechten und Pflichten) wie z.B. Fördermitglieder, Ehrenmitglieder
Sonderrechte für Mitglieder
Beitragspflichten und Sonderleistungen wie z.B. Umlagen
die kommissarische Berufung von Vorstandsmitgliedern (Selbstergänzung des Vorstandes)

**Comment by nuest** [comment]
Ziel: Institutionelle Mitglieder ermöglichen

**Comment by nuest** [comment]
Änderungsvorschlag:

> "Ordentliches Mitglied des Vereins kann jede voll geschäftsfähige natürliche Person oder Forschungseinrichtung werden, die seine Ziele unterstützt. Fördermitglied kann jede natürliche oder juristische Person werden."

**Comment by nuest** [comment]
**Entscheidung**

Wir nehmen "juristische Person", da der Vorstand sowieso über Aufnahmen entscheidet.

**Comment by nuest** [comment]
Weitergehende Änderungen (Ehrenmitglieder, kommissarische Berufung, ...) können durchaus von der Mitgliederversammlung per Beschluss geändert werden, nur muss dieser Beschluss eben eine Satzungsänderung umfassen.
